version: '3.8'

services:
  # Servicio de la Base de Datos
  db:
    image: postgres:15
    container_name: face_access_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123 # Contraseña predeterminada para el entorno Docker
      POSTGRES_DB: face_access_db
    ports:
      - "25432:5432" # Mapea la BD a un puerto diferente en la máquina host por si ya tienes postgres instalado en tu Linux
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Servicio del Backend (Python FastAPI)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: face_access_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Pasa la conexión a la instancia de DB de este Docker (usando el nombre 'db')
      - DATABASE_URL=postgresql://postgres:password123@db:5432/face_access_db
    depends_on:
      - db

volumes:
  pgdata:
